### ISSUE TITLE
Load error on 2021.5.4

### ISSUE THREAD

**Issue by tjhiwa** [thomasloven/hass-favicon#21]
HA gives error when loading on v2021.5.4.

Logger: homeassistant.config_entries
Source: custom_components/favicon/__init__.py:161
First occurred: 1:37:19 PM (1 occurrences)
Last logged: 1:37:19 PM

Error setting up entry for favicon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/favicon/__init__.py", line 45, in async_setup_entry
    return await _update_listener(hass, config_entry)
  File "/config/custom_components/favicon/__init__.py", line 59, in _update_listener
    return await apply_hooks(hass)
  File "/config/custom_components/favicon/__init__.py", line 161, in apply_hooks
    frontend.MANIFEST_JSON["icons"] = data["manifest_icons"].copy()
TypeError: 'Manifest' object does not support item assignment

**Comment by tjhiwa** [comment]
Saw the update.
