### ISSUE TITLE
Home Assistant 2024.9 compatibility (async_update_entry)

### ISSUE THREAD

**Issue by nickolay** [thomasloven/hass-favicon#37]
I've just installed this on 2024.7.4 and it works, but there's a warning:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184

Detected that custom integration 'favicon' sets "options" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at `custom_components/favicon/__init__.py, line 44: config_entry.options = config_entry.data`, please report it to the author of the 'favicon' custom integration

https://developers.home-assistant.io/blog/2024/02/12/async_update_entry/

Just a heads-up.

**Comment by nkkm888** [comment]
same here:
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'favicon' sets "options" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/favicon/__init__.py, line 44: config_entry.options = config_entry.data, please report it to the author of the 'favicon' custom integration

**Comment by tykeal** [comment]
Just installed this on a brand new 2024.11 and this is what I'm getting:

```
2024-11-20 10:50:12.865 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for favicon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/favicon/__init__.py", line 44, in async_setup_entry
    config_entry.options = config_entry.data
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 463, in __setattr__
    raise AttributeError(
AttributeError: options cannot be changed directly, use async_update_entry instead
```

As such the integration is failing to load or do any configuration :(

**Comment by saschaludwig** [comment]
Is someone aware of another extension that can change the sidebar name, like hass-favicon?

**Comment by nccchirag** [comment]
https://github.com/Snuffy2/hass-favicon
